/* -- WPPA+ Runtime parameters
/*
/* Dynamicly Created on 2016-04-26T08:24:30+00:00
/*
*/

	/* Check if wppa.js and jQuery are present */
	if (typeof(_wppaSlides) == 'undefined') alert('There is a problem with your theme. The file wppa.js is not loaded when it is expected (Errloc = wppa_kickoff).');
	if (typeof(jQuery) == 'undefined') alert('There is a problem with your theme. The jQuery library is not loaded when it is expected (Errloc = wppa_kickoff).');

	wppaVersion = "6-4-09-007";
	wppaDebug = false;
	wppaBackgroundColorImage = "#eeeeee";
	wppaPopupLinkType = "photo";
	wppaAnimationType = "fadeover";
	wppaAnimationSpeed = 800;
	wppaThumbnailAreaDelta = 14;
	wppaTextFrameDelta = 181;
	wppaBoxDelta = 14;
	wppaSlideShowTimeOut = 2500;
	wppaPreambule = 5;
	wppaFilmShowGlue = true;
	wppaSlideShow = "幻灯片";
	wppaStart = "开始";
	wppaStop = "停止";
	wppaSlower = "较慢";
	wppaFaster = "较快";
	wppaPhoto = "照片";
	wppaOf = "共";
	wppaPreviousPhoto = "以前的照片";
	wppaNextPhoto = "下一张照片";
	wppaPrevP = "上一条.";
	wppaNextP = "下一页";
	wppaAvgRating = "平均评级";
	wppaMyRating = "我的评分";
	wppaAvgRat = "平均";
	wppaMyRat = "挖";
	wppaDislikeMsg = "您标记这是不恰当的图像。";
	wppaMiniTreshold = 500;
	wppaRatingOnce = false;
	wppaPleaseName = "填写你的名字";
	wppaPleaseEmail = "请输入一个有效的email地址";
	wppaPleaseComment = "请输入注释";
	wppaHideWhenEmpty = false;
	wppaBGcolorNumbar = "#cccccc";
	wppaBcolorNumbar = "#cccccc";
	wppaBGcolorNumbarActive = "#333333";
	wppaBcolorNumbarActive = "#333333";
	wppaFontFamilyNumbar = "";
	wppaFontSizeNumbar = "px";
	wppaFontColorNumbar = "#777777";
	wppaFontWeightNumbar = "normal";
	wppaFontFamilyNumbarActive = "";
	wppaFontSizeNumbarActive = "px";
	wppaFontColorNumbarActive = "#777777";
	wppaFontWeightNumbarActive = "bold";
	wppaNumbarMax = "10";
	wppaLang = "zh";
	wppaNextOnCallback = false;
	wppaStarOpacity = 0.2;
	wppaSlideWrap = true;
	wppaEmailRequired = "required";
	wppaSlideBorderWidth = 0;
	wppaAllowAjax = true;
	wppaUsePhotoNamesInUrls = false;
	wppaThumbTargetBlank = false;
	wppaRatingMax = 5;
	wppaRatingDisplayType = "graphic";
	wppaRatingPrec = 2;
	wppaStretch = false;
	wppaMinThumbSpace = 4;
	wppaThumbSpaceAuto = true;
	wppaMagnifierCursor = "magnifier-small.png";
	wppaArtMonkyLink = "none";
	wppaAutoOpenComments = true;
	wppaUpdateAddressLine = true;
	wppaFilmThumbTitle = "双击启动/停止运行的幻灯片放映";
	wppaVoteForMe = "Vote for me!";
	wppaVotedForMe = "Voted for me";
	wppaSlideSwipe = false;
	wppaMaxCoverWidth = 1024;
	wppaDownLoad = "下载";
	wppaSlideToFullpopup = false;
	wppaComAltSize = 75;
	wppaBumpViewCount = true;
	wppaShareHideWhenRunning = true;
	wppaFotomoto = false;
	wppaArtMonkeyButton = true;
	wppaFotomotoHideWhenRunning = false;
	wppaCommentRequiredAfterVote = false;
	wppaFotomotoMinWidth = 400;
	wppaShortQargs = true;
	wppaOvlHires = false;
	wppaSlideVideoStart = false;
	wppaSlideAudioStart = false;
	wppaAudioHeight = 16;
	wppaRel = "data-rel";
	wppaStartSymbolUrl = "http://localhost/cert_website_2016/web/back-end/wp-content/plugins/wp-photo-album-plus/images/start.png";
	wppaPauseSymbolUrl = "http://localhost/cert_website_2016/web/back-end/wp-content/plugins/wp-photo-album-plus/images/pause.png";
	wppaStopSymbolUrl = "http://localhost/cert_website_2016/web/back-end/wp-content/plugins/wp-photo-album-plus/images/stop.png";
	wppaStartPauseSymbolSize = "48";
	wppaStartPauseSymbolBradius = "24";
	wppaStopSymbolSize = "48";
	wppaStopSumbolBradius = "24";
	wppaOvlRadius = 12;
	wppaOvlBorderWidth = 8;
	wppaOvlLeftSymbolUrl = "http://localhost/cert_website_2016/web/back-end/wp-content/plugins/wp-photo-album-plus/images/prev-black.gif";
	wppaOvlRightSymbolUrl = "http://localhost/cert_website_2016/web/back-end/wp-content/plugins/wp-photo-album-plus/images/next-black.gif";
	wppaLeftRightSymbolSize = 32;
	wppaLeftRightSymbolBradius = 4;
	